# Generated by Django 4.2.11 on 2024-04-01 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
                ('location', models.CharField(max_length=100, verbose_name='場所')),
                ('description', models.TextField(verbose_name='説明')),
                ('image', models.URLField(blank=True, null=True, verbose_name='画像URL')),
            ],
            options={
                'db_table': 'campground',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('rating', models.CharField(max_length=10, verbose_name='レーティング')),
                ('campground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campgrounds.campground', verbose_name='キャンプ場')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
