# Generated by Django 4.2.11 on 2024-04-02 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campgrounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
            preserve_default=False,
        ),
    ]
