# Generated by Django 4.2.11 on 2024-03-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campground',
            old_name='name',
            new_name='title',
        ),
    ]
