# Generated by Django 4.2.11 on 2024-04-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0003_review_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campground',
            name='image',
        ),
        migrations.AddField(
            model_name='campground',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真1'),
        ),
        migrations.AddField(
            model_name='campground',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真2'),
        ),
        migrations.AddField(
            model_name='campground',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='写真3'),
        ),
    ]
