# Generated by Django 4.2.11 on 2024-03-26 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0003_campground_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campground',
            old_name='image',
            new_name='images',
        ),
    ]
