# Generated by Django 4.2.11 on 2024-03-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0004_rename_image_campground_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campground',
            name='images',
        ),
        migrations.AddField(
            model_name='campground',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
