# Generated by Django 4.2.11 on 2024-04-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0004_remove_campground_image_campground_photo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campground',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='campground',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='campground',
            name='photo3',
        ),
        migrations.AddField(
            model_name='campground',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像1'),
        ),
        migrations.AddField(
            model_name='campground',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像2'),
        ),
        migrations.AddField(
            model_name='campground',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像3'),
        ),
    ]
