# Generated by Django 4.2.11 on 2024-04-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0005_remove_campground_photo1_remove_campground_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='image1',
            field=models.ImageField(default='XXX.jpg', upload_to='', verbose_name='画像1'),
            preserve_default=False,
        ),
    ]
