# Generated by Django 4.2.11 on 2024-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0005_remove_campground_images_campground_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='description',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='campground',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='画像URL'),
        ),
        migrations.AlterField(
            model_name='campground',
            name='location',
            field=models.CharField(max_length=100, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='campground',
            name='price',
            field=models.PositiveIntegerField(verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='campground',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
