# Generated by Django 4.2.11 on 2024-04-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0006_alter_campground_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='geometry',
            field=models.JSONField(default={'geometry': [135.792955, 34.509407]}, verbose_name='geometry'),
            preserve_default=False,
        ),
    ]
