# Generated by Django 4.2.11 on 2024-03-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0006_alter_campground_description_alter_campground_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='レーティング')),
                ('campground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campgrounds.campground', verbose_name='キャンプ場')),
            ],
            options={
                'verbose_name_plural': 'Review',
            },
        ),
    ]
