# Generated by Django 4.2.11 on 2024-05-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0007_campground_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='image1',
            field=models.ImageField(max_length=150, upload_to='', verbose_name='画像1'),
        ),
        migrations.AlterField(
            model_name='campground',
            name='image2',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='', verbose_name='画像2'),
        ),
        migrations.AlterField(
            model_name='campground',
            name='image3',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='', verbose_name='画像3'),
        ),
    ]
