# Generated by Django 4.2.11 on 2024-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campgrounds', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=10, verbose_name='レーティング'),
        ),
    ]
